#!/usr/bin/env bash
#this is a while loop that displays bad luck for the 4th iteration and good luck for the 8th and Holberton School 

i=1
while [ $i -lt 11 ];do 
	if (( i == 4));then
	echo bad luck
	elif (( i == 8 ));then
	echo good luck; else
	echo Holberton School
	fi
	(( i++ ))
done	









